site_name: Katz Davis Rig Documentation
site_url: https://mydomain.org/mysite
theme:
  name: material

nav:
  - Overview: index.md
  - Hardware: hardware.md
  - Cleaning: cleaning.md
  - Software: software.md
  - Troubleshooting: troubleshooting.md
  - Experimental Protocols: experimental-protocols.md
  - Data Exporting: data-exporting.md
  - Basic Analysis Tools: BAT-install.md
  - Data Analysis: data-analysis.md
